# Himma — runtime secrets boundary (docs/37 §32; docs/38 §10/§11).
#
# Terraform creates secret CONTAINERS only. Values are either
#   (a) generated by infrastructure with no plaintext in state — the runtime
#       LOGIN passwords are minted by `db:provision-roles` from values the
#       operator writes into these secrets (see infra/README.md bootstrap),
#   (b) supplied externally by the owner/ops (Stripe TEST keys, peppers,
#       Cognito public config, evidence storage key), or
#   (c) managed by RDS (the master/schema-owner password — see the database
#       module).
# No secret VERSION is ever written by Terraform: an empty container makes
# the dependent task fail closed at start (the application refuses missing
# mandatory variables). The migration/provisioning task additionally reads
# the three runtime password secrets (docs/38 §10) — that scoping lives in
# the compute module's per-invocation execution roles.
#
# One secret per consumer so IAM can scope each task role to exactly its own
# ARNs (docs/38 §10): api / worker / maintenance DB URLs are three secrets.

terraform {
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 6.0" }
  }
}

variable "name" { type = string }
variable "environment" { type = string }
variable "kms_key_id" {
  type    = string
  default = ""
}
variable "recovery_window_days" {
  type    = number
  default = 30
}
variable "tags" {
  type    = map(string)
  default = {}
}

locals {
  tags = merge(var.tags, { "himma:environment" = var.environment, "himma:component" = "secrets" })
  # name → { description, consumer }  (consumer drives IAM scoping)
  secrets = {
    "db/api" = {
      description = "JSON {\"password\": ...} for himma_api — the API task injects it as DATABASE_PASSWORD; the provisioning task reads it to create/rotate the login. Generated by infra/scripts/bootstrap-db-secrets.sh."
      consumer    = "api"
    }
    "db/worker" = {
      description = "JSON {\"password\": ...} for himma_worker."
      consumer    = "worker"
    }
    "db/maintenance" = {
      description = "JSON {\"password\": ...} for himma_maintenance_runner."
      consumer    = "maintenance"
    }
    "app/peppers" = {
      description = "HIMMA_STAFF_INVITATION_PEPPER + HIMMA_MFA_RECOVERY_PEPPER as JSON (≥32 chars each; operator-generated; never the dev/test values)."
      consumer    = "api"
    }
    "stripe/test" = {
      description = "STRIPE_SECRET_KEY (TEST-mode key ONLY — the driver refuses live keys) + STRIPE_WEBHOOK_SECRET [+ STRIPE_WEBHOOK_SECRET_RETIRING] as JSON. Absent = payments unavailable."
      consumer    = "payments"
    }
    "evidence/s3" = {
      description = "EVIDENCE_S3_ACCESS_KEY_ID + EVIDENCE_S3_SECRET_ACCESS_KEY as JSON for the evidence bucket (docs/36 IN-06/VE-01). Absent = evidence surface fail-closed 404."
      consumer    = "api"
    }
    "auth/bootstrap" = {
      description = "HIMMA_BOOTSTRAP_SECRET + HIMMA_BOOTSTRAP_CONFIRMATION — one-time admin bootstrap (bootstrap:admins); operator-run, then rotated/cleared."
      consumer    = "migrate"
    }
  }
}

resource "aws_secretsmanager_secret" "this" {
  for_each                = local.secrets
  name                    = "himma/${var.environment}/${each.key}"
  description             = each.value.description
  kms_key_id              = var.kms_key_id != "" ? var.kms_key_id : null
  recovery_window_in_days = var.recovery_window_days
  tags                    = merge(local.tags, { "himma:consumer" = each.value.consumer })
}

output "arns" {
  description = "Secret name → ARN."
  value       = { for k, s in aws_secretsmanager_secret.this : k => s.arn }
}

output "by_consumer" {
  description = "consumer → list of ARNs that consumer may read (IAM scoping input)."
  value = {
    for consumer in distinct([for s in local.secrets : s.consumer]) :
    consumer => [for k, s in aws_secretsmanager_secret.this : s.arn if local.secrets[k].consumer == consumer]
  }
}
