/**
 * RI-3 — the booking flow's COMMERCE controller: the frontend idempotency
 * authority (owner RI-3 §10) plus hold lifecycle discipline.
 *
 * Key rules (binding):
 * - One STABLE idempotency key per material commercial intent. The same
 *   intent + any retry (double tap, timeout, app retry, recoverable
 *   reload) reuses the SAME key, so the certified backend replays the
 *   same effect instead of doubling capacity or commerce.
 * - A NEW key exists only when the material intent changes: the hold key
 *   is bound to (program, option, unit, participant, quote); the confirm
 *   key to its holdId; the checkout key to (holdId, quoteId).
 * - Keys are never regenerated by render, press, or navigation.
 *
 * Hold rules:
 * - Claiming with the same signature reuses the same key → the certified
 *   claim replays the same hold (never a second seat).
 * - A MATERIAL draft change releases the previous hold explicitly
 *   (idempotent release; expiry stays authoritative if release is lost).
 * - Nothing here infers validity from the device clock for mutations —
 *   the server refuses expired holds and the UI maps the truth.
 */
import type { CapacityHold, CommerceApi } from '@/services/contracts/commerce';

/** Collision-resistant opaque key (8–128 chars per the certified contract). */
export function newIdempotencyKey(): string {
  const cryptoApi = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (cryptoApi?.randomUUID !== undefined) return cryptoApi.randomUUID();
  // Fallback for runtimes without crypto.randomUUID — an idempotency key
  // needs uniqueness, not unpredictability.
  return `idk-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 12)}-${Math.random()
    .toString(36)
    .slice(2, 12)}`;
}

/** The material commercial intent for a hold — any change = a new intent. */
export interface HoldIntent {
  programId: string;
  optionId: string;
  unitKind: 'session' | 'campWeek' | 'enrolmentCohort';
  unitId: string;
  participantId: string;
  quoteId: string;
}

export function holdSignature(intent: HoldIntent): string {
  return [
    intent.programId,
    intent.optionId,
    intent.unitKind,
    intent.unitId,
    intent.participantId,
    intent.quoteId,
  ].join('|');
}

interface HeldState {
  signature: string;
  holdKey: string;
  hold: CapacityHold;
  confirmKey?: string;
  checkoutKey?: string;
}

export class BookingCommerceController {
  private held: HeldState | undefined;
  private pendingHoldKey: { signature: string; key: string } | undefined;
  private releaseKeys = new Map<string, string>();

  constructor(private readonly api: CommerceApi) {}

  get hold(): CapacityHold | undefined {
    return this.held?.hold;
  }

  get currentSignature(): string | undefined {
    return this.held?.signature;
  }

  /**
   * Claim (or reuse) the authoritative hold for this intent. Same
   * signature → same key → the certified claim replays the same hold.
   * A different signature first releases the previous hold explicitly.
   */
  async ensureHold(intent: HoldIntent): Promise<CapacityHold> {
    const signature = holdSignature(intent);
    if (this.held !== undefined && this.held.signature === signature) {
      return this.held.hold;
    }
    if (this.held !== undefined && this.held.signature !== signature) {
      await this.releaseCurrentHold();
    }
    // The key is created ONCE per signature and survives failed attempts —
    // a timeout retry replays, it never claims twice.
    if (this.pendingHoldKey === undefined || this.pendingHoldKey.signature !== signature) {
      this.pendingHoldKey = { signature, key: newIdempotencyKey() };
    }
    const hold = await this.api.claimHold({
      unitKind: intent.unitKind,
      unitId: intent.unitId,
      participantId: intent.participantId,
      quoteId: intent.quoteId,
      idempotencyKey: this.pendingHoldKey.key,
    });
    this.held = { signature, holdKey: this.pendingHoldKey.key, hold };
    return hold;
  }

  /** Stable per-hold confirmation key — a retry replays the same commit. */
  confirmKeyFor(holdId: string): string {
    if (this.held?.hold.holdId === holdId) {
      this.held.confirmKey ??= newIdempotencyKey();
      return this.held.confirmKey;
    }
    return newIdempotencyKey();
  }

  /** Stable per-(hold, quote) checkout key — W5-5 replays the same
   *  hosted session while the Himma hold lives. */
  checkoutKeyFor(holdId: string): string {
    if (this.held?.hold.holdId === holdId) {
      this.held.checkoutKey ??= newIdempotencyKey();
      return this.held.checkoutKey;
    }
    return newIdempotencyKey();
  }

  /**
   * Explicit, idempotent release of the current hold (customer abandoned
   * the intent). Failures are swallowed — server-side expiry remains the
   * authority; the local state is forgotten either way.
   */
  async releaseCurrentHold(): Promise<void> {
    const held = this.held;
    this.held = undefined;
    this.pendingHoldKey = undefined;
    if (held === undefined) return;
    let key = this.releaseKeys.get(held.hold.holdId);
    if (key === undefined) {
      key = newIdempotencyKey();
      this.releaseKeys.set(held.hold.holdId, key);
    }
    try {
      await this.api.releaseHold(held.hold.holdId, key);
    } catch {
      // Expiry is authoritative; a lost release changes nothing.
    }
  }

  /** Forget local hold state WITHOUT a release call (the server already
   *  reported it expired/consumed — nothing to release). */
  forgetHold(): void {
    this.held = undefined;
    this.pendingHoldKey = undefined;
  }
}
