/**
 * S6-3 Final Correction — the ONE canonical occurrence derivation authority
 * (docs/35 §26–§28; owner items 5–6, 15–17).
 *
 * Both the derived customer Calendar and credential issuance validate
 * CampWeek/Cohort occurrences through THESE helpers — never through
 * separate expansion rules that could drift. The canonical identity:
 *
 *  - Session: `session_id` (unchanged — not represented here);
 *  - CampWeek: every Asia/Dubai civil date in `[start_date, end_date]` is
 *    exactly one running occurrence at the camp's single daily window
 *    (V1 has no closure/exception-day semantics — none are invented);
 *  - Cohort: `occurrence_date + occurrence_start_time`, generated by the
 *    CURRENT canonical meeting model (active association → active
 *    `recurring_schedule` ∩ cohort/schedule windows, weekday match, minus
 *    `exception_dates`). Date-only identity is FORBIDDEN: two schedules
 *    may legally meet on one civil date at different times.
 *
 * All civil-date math uses the platform's canonical Asia/Dubai timezone
 * (structurally pinned by `recurring_schedule`'s CHECK; fixed UTC+4, no
 * DST) — never the device timezone, and never `occurred_at`.
 */

const DUBAI_OFFSET_MS = 4 * 60 * 60 * 1000;

/** The Asia/Dubai civil date (YYYY-MM-DD) of an instant. */
export function dubaiDateOf(instant: Date): string {
  return new Date(instant.getTime() + DUBAI_OFFSET_MS).toISOString().slice(0, 10);
}

/** The instant at which a Dubai civil date + HH:MM[:SS] time occurs. */
export function dubaiInstant(date: string, time: string): Date {
  const normalized = time.length === 5 ? `${time}:00` : time.slice(0, 8);
  return new Date(new Date(`${date}T${normalized}.000Z`).getTime() - DUBAI_OFFSET_MS);
}

/** Dubai weekday (0 = Sunday … 6 = Saturday) of a civil date. */
export function dubaiWeekdayOf(date: string): number {
  return new Date(`${date}T00:00:00.000Z`).getUTCDay();
}

/** Civil dates from `fromDate` (inclusive) to `toDateExclusive`. */
export function* civilDates(fromDate: string, toDateExclusive: string): Generator<string> {
  let cursor = new Date(`${fromDate}T00:00:00.000Z`);
  const end = new Date(`${toDateExclusive}T00:00:00.000Z`);
  while (cursor < end) {
    yield cursor.toISOString().slice(0, 10);
    cursor = new Date(cursor.getTime() + 24 * 60 * 60 * 1000);
  }
}

/** Normalize a time literal to HH:MM (the canonical minute precision). */
export function toMinuteTime(time: string): string {
  return time.slice(0, 5);
}

export interface OccurrenceRef {
  date: string; // YYYY-MM-DD (Asia/Dubai civil date)
  startTime: string; // HH:MM
  endTime: string; // HH:MM
}

export interface CampSpan {
  startDate: string; // YYYY-MM-DD inclusive
  endDate: string; // YYYY-MM-DD inclusive
  dailyStartTime: string; // HH:MM[:SS]
  dailyEndTime: string; // HH:MM[:SS]
}

/** Every canonical CampWeek occurrence intersecting [fromDate, toDateExclusive). */
export function expandCampOccurrences(
  span: CampSpan,
  fromDate: string,
  toDateExclusive: string,
): OccurrenceRef[] {
  const occurrences: OccurrenceRef[] = [];
  for (const date of civilDates(fromDate, toDateExclusive)) {
    if (date < span.startDate || date > span.endDate) continue;
    occurrences.push({
      date,
      startTime: toMinuteTime(span.dailyStartTime),
      endTime: toMinuteTime(span.dailyEndTime),
    });
  }
  return occurrences;
}

/** One canonical cohort meeting pattern row (an ACTIVE association's ACTIVE
 *  `recurring_schedule` — callers filter states in their bounded read). */
export interface CohortScheduleRow {
  weekdays: number[];
  start_time: string; // HH:MM[:SS]
  end_time: string; // HH:MM[:SS]
  effective_start: string; // YYYY-MM-DD
  effective_end: string | null; // YYYY-MM-DD
  exception_dates: string[]; // YYYY-MM-DD[]
}

export interface CohortWindow {
  effectiveStart: string; // YYYY-MM-DD inclusive
  effectiveEnd: string; // YYYY-MM-DD inclusive
}

/**
 * Every canonical Cohort occurrence intersecting [fromDate, toDateExclusive)
 * — the single derivation the Calendar expands with and credential issuance
 * validates against. Two schedules colliding on the same (date, startTime)
 * describe the SAME customer-visible occurrence and are de-duplicated.
 */
export function expandCohortOccurrences(
  schedules: CohortScheduleRow[],
  cohort: CohortWindow,
  fromDate: string,
  toDateExclusive: string,
): OccurrenceRef[] {
  const occurrences: OccurrenceRef[] = [];
  const seen = new Set<string>();
  for (const schedule of schedules) {
    const startTime = toMinuteTime(schedule.start_time);
    const endTime = toMinuteTime(schedule.end_time);
    const exceptions = new Set(schedule.exception_dates);
    for (const date of civilDates(fromDate, toDateExclusive)) {
      if (date < cohort.effectiveStart || date > cohort.effectiveEnd) continue;
      if (date < schedule.effective_start) continue;
      if (schedule.effective_end !== null && date > schedule.effective_end) continue;
      if (!schedule.weekdays.includes(dubaiWeekdayOf(date))) continue;
      if (exceptions.has(date)) continue;
      const key = `${date}:${startTime}`;
      if (seen.has(key)) continue;
      seen.add(key);
      occurrences.push({ date, startTime, endTime });
    }
  }
  occurrences.sort((a, b) =>
    a.date < b.date ? -1 : a.date > b.date ? 1 : a.startTime < b.startTime ? -1 : 1,
  );
  return occurrences;
}

/** The next civil date after `date` (for single-date expansion bounds). */
export function nextCivilDate(date: string): string {
  return new Date(new Date(`${date}T00:00:00.000Z`).getTime() + 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);
}
